% cf_n_plotter.m generates figure 7- stochastic simulations of multiple column devices w fixed total flow. It requires the file
% 'cf_n.xlsx' generated by running the simulation file 'clog_sim.m'

clear all
syms z(x) t  %set up the symbolic function for the mean-field equation


% read and store the stochastic data from the Excel sheets
Tqq_1 = table2array(readtable('cf_n.xlsx','Sheet','q1-Q0')); 
Tq2 = table2array(readtable('cf_n.xlsx','Sheet','q2Q0'));
Tq = table2array(readtable('cf_n.xlsx','Sheet','qQ0'));
% read and store the theoretic data from the Excel sheets
Tq2exact = table2array(readtable('nb_cf_theory_q2Q0.xlsx','Sheet',1));
Tqexact = table2array(readtable('nb_cf_theory_qQ0.xlsx','Sheet',1));



%% create the plots for Tclog and fclog


% create the labels for the legend
label1 = 'stochastic, $\lambda = \alpha \tilde{q}(1-\tilde{q}/2)$';
label2 = 'stochastic, $\lambda =  \alpha m \tilde{q}^2$';
label3 = 'stochastic, $\lambda =  \alpha \tilde{q}$';
label22 = 'theory, \hspace{0.41cm}    $\lambda =  \alpha m \tilde{q}^2$';
label33 = 'theory,  \hspace{0.41cm}  $\lambda =  \alpha \tilde{q}$';

fontsz = 12; %set the font size for the plot
markersz = [5,6]; %set the marker sizes for the plot
tilez = tiledlayout(2,1); %set up the tiles for the plot

%%%% Tclog plot
% Tile 1
at1 = nexttile;
% %%%%lambda = q(1-q) plot
% stochastic data error bars
errorbar(Tqq_1(:,8),Tqq_1(:,1), Tqq_1(:,3), '.','HandleVisibility','off', 'MarkerEdgeColor', 'none');
hold on;
% stochastic data points
plot(Tqq_1(:,8),Tqq_1(:,1), 'o','MarkerSize', markersz(2), 'MarkerEdgeColor',[0 .95 .95],'MarkerFaceColor',[0 .95 .95], 'DisplayName', label1)
hold on;
% %%%%lambda = q plot
% exact solution
plot(Tqexact(:,1), Tqexact(:,2), '--', 'lineWidth', 3,'Color','m', 'DisplayName', label33)
hold on;
% stochastic error bars 
errorbar(Tq(:,8),Tq(:,1), Tq(:,3), '.','HandleVisibility','off', 'MarkerEdgeColor', 'none');
hold on;
% stochastic data points
plot(Tq(:,8),Tq(:,1), '^','MarkerSize', markersz(1),'MarkerEdgeColor',[0.4940 0.1840 0.5560],'MarkerFaceColor',[0.4940 0.1840 0.5560], 'DisplayName', label3)
hold on;
% %%%%lambda = q^2 plot
% stochastic data points
plot(Tq2exact(:,1), Tq2exact(:,2),'-.', 'lineWidth', 3, 'Color', [0.6350 0.0780 0.1840],'DisplayName', label22) ;
hold on;
% stochastic data error bars
errorbar(Tq2(:,8),Tq2(:,1), Tq2(:,3), '.','HandleVisibility','off', 'MarkerEdgeColor', 'none');
hold on;
plot(Tq2(:,8),Tq2(:,1), 'd','MarkerSize', markersz(1), 'MarkerEdgeColor','r','MarkerFaceColor','r', 'DisplayName', label2)





% set the plot legend and axis labels
legend( 'Interpreter','latex','Color','none','EdgeColor',[0.5 0.5 0.5] );
legend(  'Location', 'best', 'FontSize',fontsz );
xlabel('$n$','Interpreter','latex');
ylabel('$ T_\textbf{clog} $ (a.u.) ','Interpreter','latex');
set(gca, 'fontsize', fontsz);
set(gca, 'fontName','Times New Roman');
set(gca, 'YScale', 'log')
set(gca, 'XScale', 'log')

  
% f plot  
  % Tile 2
at2 = nexttile;  
  
  % lambda = q(1-q) plot, stochastic
  % plot the error bars for this data set
errorbar(Tqq_1(:,8),Tqq_1(:,2), Tqq_1(:,4), '.','HandleVisibility','off', 'MarkerEdgeColor', 'none');
hold on;
plot(Tqq_1(:,8),Tqq_1(:,2), 'o','MarkerSize', markersz(2), 'MarkerEdgeColor',[0 .95 .95],'MarkerFaceColor',[0 .95 .95], 'DisplayName', label1)
hold on;

% lambda = q plot, stochastic
% plot the error bars for this data set
errorbar(Tq(:,8),Tq(:,2), Tq(:,4), '.','HandleVisibility','off', 'MarkerEdgeColor', 'none');
hold on;
plot(Tq(:,8),Tq(:,2), '^','MarkerSize', markersz(1),'MarkerEdgeColor',[0.4940 0.1840 0.5560],'MarkerFaceColor',[0.4940 0.1840 0.5560], 'DisplayName', label3)
hold on;

% lambda = q^2 plot, stochastic
% stochastic data error bars
errorbar(Tq2(:,8),Tq2(:,2), Tq2(:,4),'.','HandleVisibility','off', 'MarkerEdgeColor', 'none');
hold on
plot(Tq2(:,8),Tq2(:,2), 'd','MarkerSize', markersz(1), 'MarkerEdgeColor','r','MarkerFaceColor','r', 'DisplayName', label2)



% set up the figure legend, axes labels, and axes scale 
legend( 'Interpreter','latex','Color','none','EdgeColor',[0.5 0.5 0.5] );
legend(  'Location', 'SouthWest' , 'FontSize',fontsz );
xlabel('$n$','Interpreter','latex');
ylabel('$ f_\textbf{clog} $','Interpreter','latex');
set(gca, 'fontsize', fontsz);
set(gca, 'fontName','Times New Roman');
%  set(gca, 'YScale', 'log')
set(gca, 'XScale', 'log')

% remove the extra white space
tilez.TileSpacing = 'none';
tilez.Padding = 'compact';